### ISSUE TITLE
Run on a git submodule

### ISSUE THREAD

**Issue by DanielBoettner** [gollum/docker#13]
When trying to run the following **docker compose** file on a wiki cloned as a submodule I get the following error.

## Error 
- in webview
```
Rugged::OSError at /
failed to resolve path '/wiki/../.git/modules/project-name.wiki': No such file or directory
```

## docker-compose file

```yaml
version: '3'

services:
  s2iWiki:
    image: gollumwiki/gollum:master
    restart: always
    volumes:
      - .:/wiki
    ports:
      - 4567:4567
```

Is gollum maybe just not possible on submodules?

Is there a way to map the git repo correctly, maybe overriding the `.git` path?
