### ISSUE TITLE
Rugged::RepositoryError: could not find repository from '/wiki'

### ISSUE THREAD

**Issue by maxiride** [gollum/docker#8]
I've tried to fire up Gollum with this new official Docker release with this barebone docker-compose file I wrote based on the info available [here](https://github.com/gollum/gollum/wiki/Gollum-via-Docker), however after initialization I was presented with the error `Rugged::RepositoryError could not find repository from '/wiki'`

```yml
version: "3.7"

services:
  gollum:
    image: gollumorg/gollum:5.1
    container_name: gollum
    restart: always
    ports:
      - 890:8080
#    volumes:
#      - ./config.rb:/etc/gollum/config.rb
#      - wikidata:/wiki
    command:
      - "--port=8080"
#      - "--config=/etc/gollum/config.rb"
#volumes:
# wikidata:
```
After inspecting the running container with `docker exec` I found that the git repository in the /wiki direcotry hasn't been initialized, after issuing `git init` inside `/wiki` Gollum worked perfectly fine.

Indeed, in the [Dockerfile ](https://github.com/gollum/docker/blob/master/Dockerfile)used there is no initialization of the repository.

**Comment by maxiride** [comment]
Sorry I thought only now that this was intentional as one should use a mapped folder in the host with an initialized repo. Nonetheless, this approach would help in case anyone wants to use docker volume, hence the need of initializing the repo inside the image.

Let me know your thoughts.

**Comment by worldofgeese** [comment]
This just bit me when I tried to run the one command I could find on the still-open issue for an official docker image. The Hub image doesn't given any examples of a compose so I was groping in the dark on this one. As a first-time user, I think your idea on this is right. I also suggest updating the docks on the Hub image to offer an example of a minimally viable configuration.

**Comment by worldofgeese** [comment]
Using Traefik as my reverse proxy and the example given by the issue's author I was able to get a minimally viable, internet-available instance going with:
```
version: "3.7"

services:
  gollum:
    container_name: gollum
    image: gollumorg/gollum
    restart: always
    ports:
      - "4567:4567"
    volumes:
      # - ./gollum/config.rb:/etc/gollum/config.rb
      - ./gollum/wiki:/wiki
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gollum-rtr.entrypoints=https"
      - "traefik.http.routers.gollum-rtr.rule=Host(`wiki.$DOMAINNAME`)"
      - "traefik.http.routers.gollum-rtr.tls=true"
      - "traefik.http.routers.gollum-rtr.tls.certresolver=default" 
      ## HTTP Services
      - "traefik.http.routers.gollum-rtr.service=gollum-svc"
      - "traefik.http.services.gollum-svc.loadbalancer.server.port=4567"
```
